/* Data request constants:
 *****************************************************/
export const DATA_COMBINE = 'DATA_COMBINE';
export const DATA_FORMAT_REDDIT = 'DATA_FORMAT_REDDIT';
export const DATA_FORMAT_TWEETS = 'DATA_FORMAT_TWEETS';
export const DATA_REQUEST_FAILURE = 'DATA_REQUEST_FAILURE';
export const DATA_REQUEST_PENDING = 'DATA_REQUEST_PENDING';
export const DATA_REQUEST_SUCCESS = 'DATA_REQUEST_SUCCESS';

/* Flash msg constants:
 *****************************************************/
export const FLASH_MSG_HIDE = 'FLASH_MSG_HIDE';
export const FLASH_MSG_SHOW = 'FLASH_MSG_SHOW';
export const FLASH_MSG_UPDATE = 'FLASH_MSG_UPDATE';

/* Modal constants:
 *****************************************************/
export const MODAL_LOGIN_FORM = 'MODAL_LOGIN_FORM';

/* Nerd constants:
 *****************************************************/
export const NERD_UPDATE_CHECK = 'NERD_UPDATE_CHECK';
export const NERD_SETUP_UPDATE_PHASE = 'NERD_SETUP_UPDATE_PHASE';

/* Quiz constants:
 *****************************************************/
export const QUIZ_ANS_ADD = 'QUIZ_ANS_ADD';
export const QUIZ_FORM_UPDATE = 'QUIZ_FORM_UPDATE';
export const QUIZ_LIST_FAILURE = 'QUIZ_LIST_FAILURE';
export const QUIZ_LIST_PENDING = 'QUIZ_LIST_PENDING';
export const QUIZ_LIST_SUCCESS = 'QUIZ_LIST_SUCCESS';
export const QUIZ_Q_NUMBER_UPDATE = 'QUIZ_Q_NUMBER_UPDATE';
export const QUIZ_REQUEST_FAILURE = 'QUIZ_REQUEST_FAILURE';
export const QUIZ_REQUEST_PENDING = 'QUIZ_REQUEST_PENDING';
export const QUIZ_REQUEST_SUCCESS = 'QUIZ_REQUEST_SUCCESS';
export const QUIZ_RESET = 'QUIZ_RESET';
export const QUIZ_SCORE_CALCULATE = 'QUIZ_SCORE_CALCULATE';
export const QUIZ_SCREEN_UPDATE = 'QUIZ_SCREEN_UPDATE';

/* Scheduler constants:
 *****************************************************/
export const SCHEDULER_SELECT_DATE = 'SCHEDULER_SELECT_DATE';

/* Source constants:
 *****************************************************/
export const SOURCES_COMBINE = 'SOURCES_COMBINE';
export const SOURCES_COMBINED_ARRANGE_BY = 'SOURCES_COMBINED_ARRANGE_BY';
export const SOURCES_FILTER_BY_CATEGORY = 'SOURCES_FILTER_BY_CATEGORY';
export const SOURCES_INSTAGRAM_GET_FAILURE = 'SOURCES_INSTAGRAM_GET_FAILURE';
export const SOURCES_INSTAGRAM_GET_PENDING = 'SOURCES_INSTAGRAM_GET_PENDING';
export const SOURCES_INSTAGRAM_GET_SUCCESS = 'SOURCES_INSTAGRAM_GET_SUCCESS';
export const SOURCES_REDDIT_GET_FAILURE = 'SOURCES_REDDIT_GET_FAILURE';
export const SOURCES_REDDIT_GET_PENDING = 'SOURCES_REDDIT_GET_PENDING';
export const SOURCES_REDDIT_GET_SUCCESS = 'SOURCES_REDDIT_GET_SUCCESS';
export const SOURCES_RESET_FORM = 'SOURCES_RESET_FORM';
export const SOURCES_TOGGLE_SORT_UI = 'SOURCES_TOGGLE_SORT_UI';
export const SOURCES_TOGGLE_SOURCE_MUTE = 'SOURCES_TOGGLE_SOURCE_MUTE';
export const SOURCES_TWITTER_GET_FAILURE = 'SOURCES_TWITTER_GET_FAILURE';
export const SOURCES_TWITTER_GET_PENDING = 'SOURCES_TWITTER_GET_PENDING';
export const SOURCES_TWITTER_GET_SUCCESS = 'SOURCES_TWITTER_GET_SUCCESS';
export const SOURCE_ADD_FAILURE = 'SOURCE_ADD_FAILURE';
export const SOURCE_ADD_FORM_CAT = 'SOURCE_ADD_FORM_CAT';
export const SOURCE_ADD_FORM_CAT_GM = 'SOURCE_ADD_FORM_CAT_GM';
export const SOURCE_ADD_FORM_FILTER = 'SOURCE_ADD_FORM_FILTER';
export const SOURCE_ADD_FORM_SELECT = 'SOURCE_ADD_FORM_SELECT';
export const SOURCE_ADD_PENDING = 'SOURCE_ADD_PENDING';
export const SOURCE_ADD_SUCCESS = 'SOURCE_ADD_SUCCESS';
export const SOURCE_GETBYID_FAILURE = 'SOURCE_GETBYID_FAILURE';
export const SOURCE_GETBYID_PENDING = 'SOURCE_GETBYID_PENDING';
export const SOURCE_GETBYID_SUCCESS = 'SOURCE_GETBYID_SUCCESS';
export const SOURCE_GET_INSTAGRAM_FAILURE = 'SOURCE_GET_INSTAGRAM_FAILURE';
export const SOURCE_GET_INSTAGRAM_PENDING = 'SOURCE_GET_INSTAGRAM_PENDING';
export const SOURCE_GET_INSTAGRAM_SUCCESS = 'SOURCE_GET_INSTAGRAM_SUCCESS';
export const SOURCE_GET_REDDITS_FAILURE = 'SOURCE_GET_REDDITS_FAILURE';
export const SOURCE_GET_REDDITS_PENDING = 'SOURCE_GET_REDDITS_PENDING';
export const SOURCE_GET_REDDITS_SUCCESS = 'SOURCE_GET_REDDITS_SUCCESS';
export const SOURCE_INSTAGRAM = 'SOURCE_INSTAGRAM';
export const SOURCE_REDDIT = 'SOURCE_REDDIT';
export const SOURCE_REMOVE = 'SOURCE_REMOVE';
export const SOURCE_TWITTER = 'SOURCE_TWITTER';

/* UI constants:
 *****************************************************/
export const UI_BREADCRUMBS_SET_PATH = 'UI_BREADCRUMBS_SET_PATH';
export const UI_TOGGLE_LIGHTS = 'UI_TOGGLE_LIGHTS';

/* User constants:
 *****************************************************/
export const USERS_GET_FAILURE = 'USERS_GET_FAILURE';
export const USERS_GET_PENDING = 'USERS_GET_PENDING';
export const USERS_GET_SUCCESS = 'USERS_GET_SUCCESS';
export const USER_AUTH_FAILURE = 'USER_AUTH_FAILURE';
export const USER_AUTH_PENDING = 'USER_AUTH_PENDING';
export const USER_AUTH_SUCCESS = 'USER_AUTH_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';
export const USER_LOGIN_PENDING = 'USER_LOGIN_PENDING';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_SIGNUP_FAILURE = 'USER_SIGNUP_FAILURE';
export const USER_SIGNUP_PENDING = 'USER_SIGNUP_PENDING';
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
