/* Data request constants:
 *****************************************************/
export const DATA_COMBINE = 'DATA_COMBINE';
export const DATA_FORMAT_REDDIT = 'DATA_FORMAT_REDDIT';
export const DATA_REQUEST_FAILURE = 'DATA_REQUEST_FAILURE';
export const DATA_REQUEST_PENDING = 'DATA_REQUEST_PENDING';
export const DATA_REQUEST_SUCCESS = 'DATA_REQUEST_SUCCESS';
export const DATA_FORMAT_TWEETS = 'DATA_FORMAT_TWEETS';

/* Modal constants:
 *****************************************************/
export const MODAL_LOGIN_FORM = 'MODAL_LOGIN_FORM';

/* Source constants:
 *****************************************************/
export const SOURCE_ADD_FAILURE = 'SOURCE_ADD_FAILURE';
export const SOURCE_ADD_PENDING = 'SOURCE_ADD_PENDING';
export const SOURCE_ADD_SUCCESS = 'SOURCE_ADD_SUCCESS';
export const SOURCE_ADD_FORM_CATEGORY = 'SOURCE_ADD_FORM_CATEGORY';
export const SOURCE_ADD_FORM_CATEGORY_GAMING =
  'SOURCE_ADD_FORM_CATEGORY_GAMING';
export const SOURCE_ADD_FORM_FILTER = 'SOURCE_ADD_FORM_FILTER';
export const SOURCE_ADD_FORM_SELECT = 'SOURCE_ADD_FORM_SELECT';
export const SOURCES_RESET_FORM = 'SOURCES_RESET_FORM';
export const SOURCE_REDDIT = 'SOURCE_REDDIT';
export const SOURCES_REDDIT_GET_FAILURE = 'SOURCES_REDDIT_GET_FAILURE';
export const SOURCES_REDDIT_GET_PENDING = 'SOURCES_REDDIT_GET_PENDING';
export const SOURCES_REDDIT_GET_SUCCESS = 'SOURCES_REDDIT_GET_SUCCESS';
export const SOURCE_TWITTER = 'SOURCE_TWITTER';
export const SOURCES_COMBINE = 'SOURCES_COMBINE';
export const SOURCES_TWITTER_GET_FAILURE = 'SOURCES_TWITTER_GET_FAILURE';
export const SOURCES_TWITTER_GET_PENDING = 'SOURCES_TWITTER_GET_PENDING';
export const SOURCES_TWITTER_GET_SUCCESS = 'SOURCES_TWITTER_GET_SUCCESS';

/* UI constants:
 *****************************************************/
export const UI_TOGGLE_LIGHTS = 'UI_TOGGLE_LIGHTS';

/* User constants:
 *****************************************************/
export const USER_AUTH_FAILURE = 'USER_AUTH_FAILURE';
export const USER_AUTH_PENDING = 'USER_AUTH_PENDING';
export const USER_AUTH_SUCCESS = 'USER_AUTH_SUCCESS';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';
export const USER_LOGIN_PENDING = 'USER_LOGIN_PENDING';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_SIGNUP_FAILURE = 'USER_SIGNUP_FAILURE';
export const USER_SIGNUP_PENDING = 'USER_SIGNUP_PENDING';
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';

export const USERS_GET_FAILURE = 'USERS_GET_FAILURE';
export const USERS_GET_PENDING = 'USERS_GET_PENDING';
export const USERS_GET_SUCCESS = 'USERS_GET_SUCCESS';
