// Imports:
import themeDefault from './theme_default.json';

// Constants:
const { light, dark } = themeDefault;

/* :
 ************************************************************/
export const lightTheme = {
  // Body:
  body: light.body,

  // Header:
  'header-sub-wrapper': light.header['header-sub-wrapper'],
  'hero-bg-2': light.header['hero-bg-2'],
  'hero-bg-img': light.header['hero-bg-img'],
  'hero-links-general-wrapper': light.header['hero-links-general-wrapper'],
  'hero-links-social-wrapper': light.header['hero-links-social-wrapper'],
  'hero-links-wrapper': light.header['hero-links-wrapper'],
  'nav-btn-active': light.header['nav-btn-active'],
  'nav-btn-comics': light.header['nav-btn-comics'],
  'nav-btn-comics:active': light.header['nav-btn-comics:active'],
  'nav-btn-comics:focus': light.header['nav-btn-comics:focus'],
  'nav-btn-comics:hover': light.header['nav-btn-comics:hover'],
  'nav-btn-gaming': light.header['nav-btn-gaming'],
  'nav-btn-gaming:active': light.header['nav-btn-gaming:active'],
  'nav-btn-gaming:focus': light.header['nav-btn-gaming:focus'],
  'nav-btn-gaming:hover': light.header['nav-btn-gaming:hover'],
  'nav-btn-home': light.header['nav-btn-home'],
  'nav-btn-home-active': light.header['nav-btn-home-active'],
  'nav-btn-home:active': light.header['nav-btn-home:active'],
  'nav-btn-home:focus': light.header['nav-btn-home:focus'],
  'nav-btn-home:hover': light.header['nav-btn-home:hover'],
  'nav-btn-link': light.header['nav-btn-link'],
  'nav-btn-link-fb-ico': light.header['nav-btn-link-fb-ico'],
  'nav-btn-link-fb-txt': light.header['nav-btn-link-fb-txt'],
  'nav-btn-link-insta-ico': light.header['nav-btn-link-inst-ico'],
  'nav-btn-link-insta-txt': light.header['nav-btn-link-inst-txt'],
  'nav-btn-link-light-toggle-ico':
    light.header['nav-btn-link-light-toggle-ico'],
  'nav-btn-link-light-toggle-txt':
    light.header['nav-btn-link-light-toggle-txt'],
  'nav-btn-link-settings-ico': light.header['nav-btn-link-settings-ico'],
  'nav-btn-link-settings-txt': light.header['nav-btn-link-settings-txt'],
  'nav-btn-link-twitter-ico': light.header['nav-btn-link-twitter-ico'],
  'nav-btn-link-twitter-txt': light.header['nav-btn-link-twitter-txt'],
  'nav-btn-link:active': light.header['nav-btn-link:active'],
  'nav-btn-link:hover': light.header['nav-btn-link:hover'],
  'nav-btn-mynerd': light.header['nav-btn-mynerd'],
  'nav-btn-mynerd-active': light.header['nav-btn-mynerd-active'],
  'nav-btn-mynerd:active': light.header['nav-btn-mynerd:active'],
  'nav-btn-mynerd:focus': light.header['nav-btn-mynerd:focus'],
  'nav-btn-mynerd:hover': light.header['nav-btn-mynerd:hover'],
  'nav-btn-mynerd:hover': light.header['nav-btn-mynerd:hover'],
  'nav-btn-tvfilm': light.header['nav-btn-tvfilm'],
  'nav-btn-tvfilm:active': light.header['nav-btn-tvfilm:active'],
  'nav-btn-tvfilm:focus': light.header['nav-btn-tvfilm:focus'],
  'nav-btn-tvfilm:hover': light.header['nav-btn-tvfilm:hover'],
  'nav-link': { a: light.header['nav-link']['a'] },
  'navbar-btn-active': light.header['navbar-btn-active'],
  'navbar-bg-custom': light.header['navbar-bg-custom'],
  'navbar-brand': light.header['navbar-brand'],
  'navbar-btn': light.header['navbar-btn'],
  'navbar-custom': light.header['navbar-custom'],
  'navbar-logo-wrapper > img': light.header['navbar-logo-wrapper > img'],
  'navbar-logo-wrapper': light.header['navbar-logo-wrapper'],
  'vertical-center': light.header['vertical-center'],

  // -
};

export const darkTheme = {
  // Body:
  body: dark.body,

  // Header:
  'header-sub-wrapper': dark.header['header-sub-wrapper'],
  'hero-bg-2': dark.header['hero-bg-2'],
  'hero-bg-img': dark.header['hero-bg-img'],
  'hero-links-general-wrapper': dark.header['hero-links-general-wrapper'],
  'hero-links-social-wrapper': dark.header['hero-links-social-wrapper'],
  'hero-links-wrapper': dark.header['hero-links-wrapper'],
  'nav-btn-active': dark.header['nav-btn-active'],
  'nav-btn-comics': dark.header['nav-btn-comics'],
  'nav-btn-comics:active': dark.header['nav-btn-comics:active'],
  'nav-btn-comics:focus': dark.header['nav-btn-comics:focus'],
  'nav-btn-comics:hover': dark.header['nav-btn-comics:hover'],
  'nav-btn-gaming': dark.header['nav-btn-gaming'],
  'nav-btn-gaming:active': dark.header['nav-btn-gaming:active'],
  'nav-btn-gaming:focus': dark.header['nav-btn-gaming:focus'],
  'nav-btn-gaming:hover': dark.header['nav-btn-gaming:hover'],
  'nav-btn-home': dark.header['nav-btn-home'],
  'nav-btn-home-active': dark.header['nav-btn-home-active'],
  'nav-btn-home:active': dark.header['nav-btn-home:active'],
  'nav-btn-home:focus': dark.header['nav-btn-home:focus'],
  'nav-btn-home:hover': dark.header['nav-btn-home:hover'],
  'nav-btn-link': dark.header['nav-btn-link'],
  'nav-btn-link-fb-ico': dark.header['nav-btn-link-fb-ico'],
  'nav-btn-link-fb-txt': dark.header['nav-btn-link-fb-txt'],
  'nav-btn-link-insta-ico': dark.header['nav-btn-link-inst-ico'],
  'nav-btn-link-insta-txt': dark.header['nav-btn-link-inst-txt'],
  'nav-btn-link-light-toggle-ico': dark.header['nav-btn-link-light-toggle-ico'],
  'nav-btn-link-light-toggle-txt': dark.header['nav-btn-link-light-toggle-txt'],
  'nav-btn-link-settings-ico': dark.header['nav-btn-link-settings-ico'],
  'nav-btn-link-settings-txt': dark.header['nav-btn-link-settings-txt'],
  'nav-btn-link-twitter-ico': dark.header['nav-btn-link-twitter-ico'],
  'nav-btn-link-twitter-txt': dark.header['nav-btn-link-twitter-txt'],
  'nav-btn-link:active': dark.header['nav-btn-link:active'],
  'nav-btn-link:hover': dark.header['nav-btn-link:hover'],
  'nav-btn-mynerd': dark.header['nav-btn-mynerd'],
  'nav-btn-mynerd-active': dark.header['nav-btn-mynerd-active'],
  'nav-btn-mynerd:active': dark.header['nav-btn-mynerd:active'],
  'nav-btn-mynerd:focus': dark.header['nav-btn-mynerd:focus'],
  'nav-btn-mynerd:hover': dark.header['nav-btn-mynerd:hover'],
  'nav-btn-mynerd:hover': dark.header['nav-btn-mynerd:hover'],
  'nav-btn-tvfilm': dark.header['nav-btn-tvfilm'],
  'nav-btn-tvfilm:active': dark.header['nav-btn-tvfilm:active'],
  'nav-btn-tvfilm:focus': dark.header['nav-btn-tvfilm:focus'],
  'nav-btn-tvfilm:hover': dark.header['nav-btn-tvfilm:hover'],
  'nav-link': { a: dark.header['nav-link']['a'] },
  'navbar-btn-active': dark.header['navbar-btn-active'],
  'navbar-bg-custom': dark.header['navbar-bg-custom'],
  'navbar-brand': dark.header['navbar-brand'],
  'navbar-btn': dark.header['navbar-btn'],
  'navbar-custom': dark.header['navbar-custom'],
  'navbar-logo-wrapper > img': dark.header['navbar-logo-wrapper > img'],
  'navbar-logo-wrapper': dark.header['navbar-logo-wrapper'],
  'vertical-center': dark.header['vertical-center'],
};
